### ISSUE TITLE
sidebar folder / file indentation issue

### ISSUE THREAD

**Issue by xaun** [jamiewilson/predawn#100]
Can you see how the folder and the file are at different indentation levels even though they are both children of analytics?

<img width="204" alt="screen shot 2015-08-26 at 4 37 47 pm" src="https://cloud.githubusercontent.com/assets/7486451/9487038/80a52480-4c11-11e5-95ae-332fe1f32de4.png">

Is that as intended? if so, can it be customised?

**Comment by xaun** [comment]
Improved my googling and found my answer.. My apologies.

**Comment by thomthom** [comment]
@xaun can you share what you found?

**Comment by xaun** [comment]
@thomthom https://github.com/jamiewilson/predawn/issues/70 :)
