### ISSUE TITLE
Tabs and sidebar titles appear italic [suffering to read]

### ISSUE THREAD

**Issue by MoradHamdy** [jamiewilson/predawn#101]
Hi there,

Titles in sidebar and and tabs look like this. Is there some solution for this issue to make font looks normal?

![tabs and sidebar titles italic issues](https://cloud.githubusercontent.com/assets/4193946/9703749/4478ba74-548d-11e5-8e12-5cc68ded250f.png)

**Comment by jamiewilson** [comment]
I believe that's an intended affect for what's called "transient" tabs. If you want, you could disable the click to preview feature  with 

```
"preview_on_click": false,
```
