### ISSUE TITLE
Files and folders are not at the same indent level

### ISSUE THREAD

**Issue by louh** [jamiewilson/predawn#102]
So this is the root level of my repository:

![screenshot 2015-09-10 16 44 00](https://cloud.githubusercontent.com/assets/2553268/9800498/43fdb8d2-57db-11e5-922d-8f3b1570e94b.png)

The `.gitignore`, `circle.yml` etc files are in the directory root, _not_ inside the `theme` folder.

This gets really annoying when I open up folders:

![screenshot 2015-09-10 16 44 12](https://cloud.githubusercontent.com/assets/2553268/9800519/5cf25c58-57db-11e5-8902-c7a2c589d41a.png)
![screenshot 2015-09-10 16 44 18](https://cloud.githubusercontent.com/assets/2553268/9800522/5fad1460-57db-11e5-9223-efbc16e12e00.png)

Things just keep looking like they're in the wrong folder when they're not :(

Any idea what's causing this?

Thanks!

**Comment by jamiewilson** [comment]
Yeah, sorry about this. It's because of previous versions of ST that don't support icons. You can immediately fix this by setting you theme to `"theme": "predawn-DEV.sublime-theme"`, but I hope to merge those two versions in the near future.

**Comment by louh** [comment]
Ahhh - that did the trick :) I hadn't realized I had a dev build of Sublime Text.

Thanks!
