### ISSUE TITLE
Would love to see a PhpStorm UI port

### ISSUE THREAD

**Issue by ianrobertdouglas** [jamiewilson/predawn#103]
Just leaving this here, in case anyone knows of the existence of a PhpStorm UI port of predawn. I've searched widely, but cannot find anything like it. In fact, I can't find any alternatives to the light and darkula UI themes.

I'm looking for something darker than darkula.

Again, the UI, not syntax.

**Comment by jamiewilson** [comment]
Thanks for the request, but I don't think I have time to add another editor. Feel free to fork!
