### ISSUE TITLE
Files are positioned 16px to the right (directories arn't)

### ISSUE THREAD

**Issue by ronald-shcc** [jamiewilson/predawn#105]
Hi,

I've got a problem on sublime text 3, in the project sidebar
```
[ico] DIRECTORY-A
     [ico] DIRECTORY-B
          [ico] file-in-directory-A
```

It should be like this:
```
[ico] DIRECTORY-A
     [ico] DIRECTORY-B
     [ico] file-in-directory-A
```

**Comment by jamiewilson** [comment]
Yeah, sorry about this. It's because of previous versions of ST that don't support icons. You can immediately fix this by setting your theme to ` "theme": "predawn-DEV.sublime-theme" `, but eventually I'll merge those two when ST3 comes out of dev.
