### ISSUE TITLE
Folder Icons Changed

### ISSUE THREAD

**Issue by markpanado** [jamiewilson/predawn#110]
The theme auto-updated this morning and the folder icons suddenly changed. How can I revert this back to orange folders?

<img width="77" alt="screen shot 2015-10-26 at 9 18 14 am" src="https://cloud.githubusercontent.com/assets/3646720/10719377/a271ed56-7bc2-11e5-8288-c98dc6f0d739.png">

**Comment by entr** [comment]
Same, build 3083, LinuxMint 17.2 x64

**Comment by Kotzilla** [comment]
+1 Please fix

**Comment by entr** [comment]
Got it. Replace 
```json
	"theme": "predawn.sublime-theme",
```
with
```json
	"theme": "predawn-DEV.sublime-theme",
```
This is also in the README, so @markpanado could close this.

**Comment by markpanado** [comment]
Wow thanks for noticing @entr! Confirmed the solution is working:

<img width="98" alt="screen shot 2015-10-26 at 3 40 29 pm" src="https://cloud.githubusercontent.com/assets/3646720/10723667/2c3f5d4a-7bf8-11e5-9a95-b830d2e94ba5.png">
