### ISSUE TITLE
1.3.4

### ISSUE THREAD

**Issue by alexmccabe** [jamiewilson/predawn#111]
The latest update removed the folder icons, have the default ST3 icons now.

**Comment by jamiewilson** [comment]
Make sure you follow the instructions for activating the correct theme for either ST3 or ST2: https://github.com/jamiewilson/predawn#activating-the-theme

**Comment by cviccaro** [comment]
Had this same issue, but using predawn-DEV, as @jamiewilson advises above, fixes the issue.  Also, technically I'd say it's not even an issue since 3062+ builds should be using predawn-DEV anyways, but I didn't myself notice that requirement until the missing folder icons forced me to do so.

**Comment by jtompkins** [comment]
I also had this issue. I didn't realize I needed to change anything though, because I'm on the stable channel, but even my stable channel build is now > 3062:

![image](https://cloud.githubusercontent.com/assets/815768/10769433/71843186-7cbc-11e5-90ea-15245ceccd7e.png)

**Comment by jamiewilson** [comment]
Yeah. ST3 is actually still in beta http://www.sublimetext.com/3. But i'm trying figure out the best way to support both ST2 and ST3. Sorry for any confusion.

**Comment by jtompkins** [comment]
Totally understandable. Thanks for a great theme!

**Comment by alexmccabe** [comment]
Oh cool, for some reason when I tried that before it didn't work. Must've typo'd it. Cheers buddy :+1:
