### ISSUE TITLE
Icons changed ?

### ISSUE THREAD

**Issue by goldo** [jamiewilson/predawn#112]
Hello,

Today I noticed my orange folder icons have disappeared, is it normal ?
http://files.afranck.com/_/ik8HaYk

It looks like a bug, isnt it ?

Thanks

**Comment by ntnhieu** [comment]
Hi,
In this morning, I open Sublime Text and it auto update some things. After that I see the same error! So, I check the build number is 3083, may be update to get some error with this theme.

**Comment by tocaibiza** [comment]
Please check the instructions. You need to use this theme name for 3082+ dev builds:

"theme": "predawn-DEV.sublime-theme"

**Comment by goldo** [comment]
But I didn't installed any dev version, I just installed with sublime
packager.

Anyway works fine with this, thank you.

> On Oct 26 2015, at 3:02 pm, Dimitar Mihaylov
&lt;notifications@github.com&gt; wrote:  

>

> Please check the instructions. You need to use this theme name for 3082+ dev
builds:

>

> "theme": "predawn-DEV.sublime-theme"

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/jamiewi
lson/predawn/issues/112#issuecomment-151142753).![](https://github.com/notific
ations/beacon/AAfrEvE8g--ldThB1iVkkPTXLWepKZc2ks5o_injgaJpZM4GVfRR.gif)

**Comment by tocaibiza** [comment]
I just shared what worked for me. Not sure why it's called "dev". :)

**Comment by jamiewilson** [comment]
Up, ST3 is still technically beta, so I opted to call it -DEV. See a more complete answer here -> #108
