### ISSUE TITLE
sidebar width defaults to narrow

### ISSUE THREAD

**Issue by rjinski** [jamiewilson/predawn#113]
The sidebar seems to default to narrow without an option to make it wide

predrawn_sidebar_narrow true/false as no effect

**Comment by jamiewilson** [comment]
It looks like your settings says `predRawn_sidebar_narrow`. I'd check that first. Let me know if you're still having trouble.

**Comment by rjinski** [comment]
Sorry, that was just a typo. 

"predawn_sidebar_narrow": true

Again, true or false has no effect.

**Comment by jamiewilson** [comment]
You might try dragging the width of your sidebar. Otherwise, have you tried quit and relaunching the app?

**Comment by rjinski** [comment]
Tested, no change.

**Comment by jamiewilson** [comment]
Hmm. Not sure what else to suggest. Maybe collapsing some folders? That's what I did here, and as you can see, it appears to working: http://quick.as/e2JpTvGk1

What version of Sublime are you running? what OS?

**Comment by rjinski** [comment]
OSX 10.11.1
Sublime Build 3083

http://postimg.org/image/6oi1h9jo3/

**Comment by rjinski** [comment]
Just verified - it works in DEV, not release. Although the orange folders are still missing *shrug*

**Comment by jamiewilson** [comment]
Okay. looks like you need to follow the instructions for avtivating the theme for ST3 (which is still actually considered a Dev build: https://github.com/jamiewilson/predawn/blob/master/README.md#activating-the-theme

**Comment by rjinski** [comment]
A dev build resolved - thank you
