### ISSUE TITLE
Icons Missing for Some File Types

### ISSUE THREAD

**Issue by kevinswarner** [jamiewilson/predawn#117]
For some reason, I am no longer seeing icons for some file types. These two files are NOT in the test directory, but rather on the root level.

![image](https://cloud.githubusercontent.com/assets/399641/11275249/5e0c1464-8ea2-11e5-8c69-421799195fe1.png)

I am using ST3. My prefs look like this...

``` javascript
{
    "color_scheme": "Packages/Colorsublime - Themes/Tomorrow_Night.tmTheme",
    "font_face": "DejaVu Sans Mono",
    "font_size": 14,
    "ignored_packages":
    [
        "Vintage"
    ],
    "predawn_findreplace_small": false,
    "predawn_quick_panel_small": false,
    "predawn_sidebar_arrows": false,
    "predawn_sidebar_large": false,
    "predawn_sidebar_medium": false,
    "predawn_sidebar_narrow": false,
    "predawn_sidebar_small": true,
    "predawn_sidebar_xlarge": false,
    "predawn_sidebar_xsmall": false,
    "predawn_tabs_active_underline": true,
    "predawn_tabs_large": false,
    "predawn_tabs_medium": true,
    "predawn_tabs_small": false,
    "save_on_focus_lost": true,
    "scroll_past_end": true,
    "theme": "predawn-DEV.sublime-theme",
    "trim_automatic_white_space": false
}
```

**Comment by VivekRagunathan** [comment]
I installed Predawn theme, and all predawn icons are missing. Any idea why?
![predawn](https://cloud.githubusercontent.com/assets/292160/11455679/4a72275c-961f-11e5-80e6-c3cea1904654.jpg)


My settings:

```json
{
	"auto_indent": true,
	"auto_match_enabled": true,
	"theme": "predawn.sublime-theme",
	"color_scheme": "Packages/Predawn/predawn.tmTheme",
	"detect_indentation": true,
	"drag_text": true,
	"find_selected_text": true,
	"font_face": "Menlo",
	"font_options":
	[
	],
	"font_size": 16,
	"highlight_line": true,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"line_numbers": true,
	"match_brackets": true,
	"match_brackets_angle": true,
	"match_brackets_braces": true,
	"match_brackets_square": true,
	"match_selection": true,
	"match_tags": true,
	"predawn_sidebar_arrows": true,
	"predawn_sidebar_large": true,
	"predawn_tabs_active_underline": true,
	"remember_open_files": true,
	"shift_tab_unindent": true,
	"smart_indent": true,
	"tab_size": 3,
	"trim_automatic_white_space": true,
	"use_tab_stops": true
}
```

**Comment by kevinswarner** [comment]
I believe you need to be running a Sublime build version 3062 or greater AND specify the dev version of the predawn theme.

    "theme": "predawn-DEV.sublime-theme"

You also need to restart Sublime.

This should get you the icons, but I still am missing icons for a few types (see top of this issue.)

**Comment by tocaibiza** [comment]
Just would like to note that the icons for SASS files are missing (recent Predawn version + Sublime Text 3, build 3083). All other icons are fine.

**Comment by VivekRagunathan** [comment]
@kevinswarner I am running build 3083, and tried 

```
"theme": "predawn-DEV.sublime-theme"
```

Doesn't work!

**Comment by feryardiant** [comment]
I also face same issue.

![predawn](https://cloud.githubusercontent.com/assets/508665/12009250/1ae45a88-aca3-11e5-9914-d06288f98664.png)

**Comment by postromantic** [comment]
the same:( no default icon for unknown file types.
any workarounds?

**Comment by jamiewilson** [comment]
Hmm. I can't reproduce this. Could you all share your OS and ST version, console logs and anything else that might help me out?

**Comment by jamiewilson** [comment]
@VivekRagunathan did you end up sorting your issues out? what version of ST are you using?

**Comment by VivekRagunathan** [comment]
@jamiewilson I was using an immediate earlier build of sublime text 3. Now I am using 3103. I am still having issues and had to change to afterglow for now.

**Comment by mikeflores** [comment]
Hi @jamiewilson. I'm using ST2 (Build 2221) and wondering how I can have the icons in my sidebar. I'm still a bit new to customizing my Sublime Text. Thanks in advance!

**Comment by feryardiant** [comment]
Hi @jamiewilson, glad to see you here.

I'm using ST3 3103 on Kubuntu 15.10 and here's my console output

```
startup, version: 3103 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/feryardiant/.config/sublime-text-3/Packages
state path: /home/feryardiant/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/feryardiant/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.304462
startup time: 1.43
first paint time: 1.45608
unsupported pixel depth
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin Alignment.Alignment
reloading plugin All Autocomplete.all_views_completions
reloading plugin Better CoffeeScript.CoffeeScript
reloading plugin BracketHighlighter.bh_core
scan: /home/feryardiant/Workspaces/Application/vendor/feryardiant/cms has been seen before, skipping (using inode) previous path: /home/feryardiant/Workspaces/Application/cms inode: 24895814
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin DocBlockr.jsdocs
reloading plugin EditorConfig.EditorConfig
reloading plugin Emmet.emmet-plugin
reloading plugin FindKeyConflicts.find_key_conflicts
reloading plugin Fold Comments.foldcomments
reloading plugin Git.git_commands
reloading plugin GitSavvy.git_savvy
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin LESS.less_completions
reloading plugin Laravel 5 Artisan.Laravel 5 Artisan
reloading plugin Origami.origami
reloading plugin PHP Companion.PHP Companion
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Pretty JSON.PrettyJson
reloading plugin SassBeautify.SassBeautify
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Stylus.Stylus
reloading plugin Sync View Scroll.syncscroll
reloading plugin Xdebug Client.main
reloading plugin sublime-github.commandline
reloading plugin sublime-github.github
reloading plugin sublime-github.sublime_github
reloading plugin sublime-github.sublime_requests
reloading plugin Babel.Babel
scan: /home/feryardiant/Workspaces/Application/res/views/backend/auth has been seen before, skipping (using inode) previous path: /home/feryardiant/Workspaces/Application/res/views/auth inode: 25158296
reloading plugin ColorPicker.sublimecp
reloading plugin PlainTasks.PlainTasks
reloading plugin Terminal.Terminal
reloading plugin phpfmt.phpfmt
plugins loaded
syncScroll starting
reloading Packages/User/phpfmt.sublime-settings
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2016-03-26 09:30:01, next run at 2016-03-26 10:30:01 or after
```

**Comment by poltorak** [comment]
I got also missing icons for coffee files, and jade files. Are they included in icon set?

**Comment by kxk** [comment]
Same here!

**Comment by olixem** [comment]
+1

**Comment by dustinkeeton** [comment]
+1

**Comment by CollegeFellow** [comment]
Hi @jamiewilson I am also facing this issue. When I use
`"theme": "predawn.sublime-theme",` all the icons are there but these are default sublime icons
and when I use
`"theme": "predawn-DEV.sublime-theme",` all the icons just disappear

I'm using ST-3126 on OS X El Capitan and here's my console output

    startup, version: 3126 osx x64 channel: stable
    executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
    working dir: /
    packages path: /Users/akshaygohil/Library/Application Support/Sublime Text 3/Packages
    state path: /Users/akshaygohil/Library/Application Support/Sublime Text 3/Local
    zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
    zip path: /Users/akshaygohil/Library/Application Support/Sublime Text 3/Installed Packages
    ignored_packages: ["Vintage"]
    pre session restore time: 0.446999
    first paint time: 0.574985
    startup time: 0.602853
    unsupported pixel depth
    reloading plugin Default.auto_indent_tag
    reloading plugin Default.block
    reloading plugin Default.comment
    reloading plugin Default.convert_syntax
    reloading plugin Default.copy_path
    reloading plugin Default.delete_word
    reloading plugin Default.detect_indentation
    reloading plugin Default.duplicate_line
    reloading plugin Default.echo
    reloading plugin Default.exec
    reloading plugin Default.fold
    reloading plugin Default.font
    reloading plugin Default.goto_line
    reloading plugin Default.history_list
    reloading plugin Default.indentation
    reloading plugin Default.install_package_control
    reloading plugin Default.kill_ring
    reloading plugin Default.mark
    reloading plugin Default.new_templates
    reloading plugin Default.open_context_url
    reloading plugin Default.open_in_browser
    reloading plugin Default.pane
    reloading plugin Default.paragraph
    reloading plugin Default.paste_from_history
    reloading plugin Default.profile
    reloading plugin Default.quick_panel
    reloading plugin Default.run_syntax_tests
    reloading plugin Default.save_on_focus_lost
    reloading plugin Default.scroll
    reloading plugin Default.set_unsaved_view_name
    reloading plugin Default.settings
    reloading plugin Default.show_scope_name
    reloading plugin Default.side_bar
    reloading plugin Default.sort
    reloading plugin Default.swap_line
    reloading plugin Default.switch_file
    reloading plugin Default.symbol
    reloading plugin Default.transform
    reloading plugin Default.transpose
    reloading plugin Default.trim_trailing_white_space
    reloading plugin CSS.css_completions
    reloading plugin Diff.diff
    reloading plugin HTML.encode_html_entities
    reloading plugin HTML.html_completions
    reloading plugin 0_package_control_loader.00-package_control
    reloading plugin 0_package_control_loader.01-pygments
    reloading plugin 0_package_control_loader.50-backrefs
    reloading plugin 0_package_control_loader.50-markupsafe
    reloading plugin 0_package_control_loader.50-python-markdown
    reloading plugin 0_package_control_loader.51-python-jinja2
    reloading plugin 0_package_control_loader.55-mdpopups
    reloading plugin All Autocomplete.all_views_completions
    reloading plugin AutoFileName.autofilename
    reloading plugin AutoFileName.getimageinfo
    reloading plugin BracketHighlighter.bh_core
    reloading plugin BracketHighlighter.bh_logging
    reloading plugin BracketHighlighter.bh_plugin
    reloading plugin BracketHighlighter.bh_regions
    reloading plugin BracketHighlighter.bh_remove
    reloading plugin BracketHighlighter.bh_rules
    reloading plugin BracketHighlighter.bh_search
    reloading plugin BracketHighlighter.bh_swapping
    reloading plugin BracketHighlighter.bh_wrapping
    reloading plugin BracketHighlighter.changes
    reloading plugin BracketHighlighter.support
    reloading plugin Color Highlighter.ColorHighlighter
    reloading plugin Color Highlighter.colors
    reloading plugin DocBlockr.jsdocs
    reloading plugin Emmet.emmet-plugin
    reloading plugin GitGutter.git_gutter
    reloading plugin GitGutter.git_gutter_change
    reloading plugin GitGutter.git_gutter_compare
    reloading plugin GitGutter.git_gutter_events
    reloading plugin GitGutter.git_gutter_handler
    reloading plugin GitGutter.git_gutter_popup
    reloading plugin GitGutter.git_helper
    reloading plugin GitGutter.view_collection
    reloading plugin HTML5.encode_html_entities
    reloading plugin HTML5.html_completions
    reloading plugin LESS.less_completions
    reloading plugin Package Control.1_reloader
    reloading plugin Package Control.2_bootstrap
    reloading plugin Package Control.Package Control
    reloading plugin SideBarEnhancements.SideBar
    reloading plugin SideBarEnhancements.SideBarAPI
    reloading plugin SideBarEnhancements.SideBarDefaultDisable
    reloading plugin SublimeCodeIntel.ordereddict
    reloading plugin SublimeCodeIntel.SublimeCodeIntel
    plugins loaded
    Emmet: No need to update PyV8
    Package Control: Skipping automatic upgrade, last run at 2016-09-30 11:58:46, next run at 2016-09-30 12:58:46 or after
    Unable to open /Users/akshaygohil/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings
    + Info: processing 'JSON': please wait...
    reloading settings Packages/User/Preferences.sublime-settings
    Could not import subprocess32 module, falling back to subprocess module
    reloading settings Packages/User/Preferences.sublime-settings

**Comment by talengix** [comment]
the orange folder icons are not displaying for me. i just see black folders. however the file type icons are displaying correctly. any idea why i can't see orange folders?
![screenshot from 2016-12-19 18-55-55](https://cloud.githubusercontent.com/assets/334387/21323238/d8e1da2c-c61c-11e6-9092-d058a2a7ebf8.png)

**Comment by erkanunluturk** [comment]
`"theme": "predawn-DEV.sublime-theme"`

**Comment by talengix** [comment]
thank you. that worked perfectly. awesome theme. cheers

**Comment by marekkaczkowski** [comment]
Same for Sublime 3126 on macOS Sierra 10.12.4 Beta (16E154a), there are no icons for yml, json, .gitignore 😩
![screen shot 2017-02-15 at 20 58 22](https://cloud.githubusercontent.com/assets/273831/22992976/9ce1b7c2-f3c1-11e6-9589-82a13a236c84.png)

**Comment by jamiewilson** [comment]
For those interested in better icon support, I highly suggest installing this package: https://github.com/ihodev/a-file-icon
