### ISSUE TITLE
Projects are empty

### ISSUE THREAD

**Issue by marcthiele** [jamiewilson/predawn#118]
Hi,

First of all: I love the theme. Really wonderful work. Only have one issue with it: if I switch a project, the sidebar is completely empty. No folders are shown anymore. If I drag a project folder onto the Sublime Text icon, it is opened correctly. But as soon as I use CTRL+CMD+P to switch the project, the sidebar is empty as shown in the screenshot. Any idea what this can be? 
![screen shot 2015-12-09 at 14 20 20](https://cloud.githubusercontent.com/assets/293397/11686328/2b7619da-9e80-11e5-877f-2d30c6d05366.png)

**Comment by jamiewilson** [comment]
Hmm. That's probably not a problem with Predawn. It looks like you might have renamed the directory your project is in or something? Maybe try Project > Refresh Folders and see what happens?

**Comment by marcthiele** [comment]
Hey Jamie,

I did this already. I am not sure if this is a problem of Predawn, but it never happened before the installation. And it is not only one project, but all I try to switch to. If I quit Seublime text and restart it, all folders and files are there again.


![screen shot 2015-12-09 at 16 50 09](https://cloud.githubusercontent.com/assets/293397/11690039/f605e360-9e94-11e5-8a65-3eb3c11a8848.png)

**Comment by jamiewilson** [comment]
Darn. Well, what happens if you open a .sublime-project file without using ctrl-shift-p?

**Comment by marcthiele** [comment]
Found what it was! It wasn't your theme indeed. I somehowmust have switched on "Show Open Files" just for one project. If that is set differently in ST3, then it causes this bug. Found the solution [here](https://github.com/SublimeTextIssues/Core/issues/62) in the post by "sentience" a bit down in the thread. But thanks for responding, Jamie.

**Comment by jamiewilson** [comment]
No problemo!
