### ISSUE TITLE
Scrollbars don't work

### ISSUE THREAD

**Issue by nkristek** [jamiewilson/predawn#119]
since the last commit scrollbars don't work as expected. I tested this on Sublime Text 2&3 on Mac and Windows. The problem is, that where the scrollbars should be, there are just rectangles which are fading from yellow to red and to yellow again.
When I download everything before the "refactoring sidebars and scrollbars"-commit the scrollbars behave as expected.

**Comment by jamiewilson** [comment]
Can you try using the [predawn-DEV version](https://github.com/jamiewilson/predawn#activating-the-theme) (for all ST builds at 3062+) since there were some major changes to the sidebar after 2.x. So if you change your `theme` to `predawn-DEV.sublime-theme`, should fix this issue for you.
