### ISSUE TITLE
Highlighting for Ecmascript 6

### ISSUE THREAD

**Issue by cawa-93** [jamiewilson/predawn#120]
Is it possible to enable or implement further syntax highlighting for Ecmascript 6 ?
![2015-12-16 12 50 10](https://cloud.githubusercontent.com/assets/1662812/11839047/91510c88-a3f3-11e5-863c-df3bc0161115.png)

Github syntax highlighting works better.
```javascript
var a;						// ok
const b;					// ok
let c;						// "let" is not highlighted

'Single quotes';			// ok
"Double quotes";			// ok
`template strings`;			// template strings is not highlighted

(function (params) {})();	// ok
(params) => {}				// In arrow function notation arguments is not highlighted
```

**Comment by ianiD** [comment]
I'm not sure if predawn handles syntax highlighting directly. It just provides color scheme/layout info. You'd need another package to make ES6 highlighting work.

I might be wrong about this, though.

**Comment by ianiD** [comment]
I made it work for me by installing [JavascriptNext](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax) and setting the syntax highlighting for all `.js` files to JavascriptNext (http://puu.sh/mrNsS/c2bf425d01.png).

**Comment by cawa-93** [comment]
JavascriptNext is just awful! It is so unpleasant that I want to tear my eyes, not to see it.

**Comment by ianiD** [comment]
The way I described it makes it use predawn's color scheme with javascriptnext's syntax highlighting. You don't need to use the javascriptnext color scheme
