### ISSUE TITLE
Sublime Text 3103 JS Syntax Highlighting

### ISSUE THREAD

**Issue by alexmccabe** [jamiewilson/predawn#122]
Since updating to ST3 3103 the syntax highlighting for JS files has changed, and has become much less clear. Now I'm wading through a sea of orange text. Every other syntax appears to be fine. In the changelog for the new update there is mention of changing the way syntax highlighting works, so I'm wondering whether a couple tweaks would sort it out? As you can see in the attached screenshot, variables and function names are the same colour, when this wasn't the case as far as I can recall.

![screenshot 2016-02-09 09 44 41](https://cloud.githubusercontent.com/assets/2529110/12912637/c836906c-cf11-11e5-9738-ceb3617f5008.png)

**Comment by jamiewilson** [comment]
@alexmccabe Oh, bummer. I just updated and this is bad. Will take a look as soon as I can. Thanks for reporting.

**Comment by alexmccabe** [comment]
It's no worries, and there's no way I will be switching off this theme because of it! I will endure ;) But there is no rush, at least not from my point of view anyway.

**Comment by jamiewilson** [comment]
I couldn't deal with that. Had to resolve immediately :) Should hit Package Control within the hour. 

Let me know if this works or if there are things that still aren't right. I think there were a handful of new syntax scopes added so I'm not sure I can replicate the way it used to be. At least it's not so much orange now though.

**Comment by epzee** [comment]
@jamiewilson thanks for the quick fix, looks much better now! I think there are some more tweaks to be made. Check `view.`, `data.` and `APP.Utils.` in this example: 

<img width="576" alt="screenshot 2016-02-10 00 55 35" src="https://cloud.githubusercontent.com/assets/621731/12935887/44d959a4-cf91-11e5-91fa-30859f550ecf.png">

**Comment by alexmccabe** [comment]
Sorry I forgot to mention I was on the -DEV part of it, variables are still orange for me on the new update. I don't know if there is anything else I should be doing? I updated the package and restarted ST3.

![screenshot 2016-02-10 12 19 18](https://cloud.githubusercontent.com/assets/2529110/12947035/8cfdccc4-cff0-11e5-9675-84a0748ab2de.png)

**Comment by matejkramny** [comment]
<img width="333" alt="screen shot 2016-02-10 at 13 27 49" src="https://cloud.githubusercontent.com/assets/797608/12948433/1c8711bc-cffa-11e5-8cde-7f2a520b7086.png">

Hello, these changes are too much!

The previous looked so much better, how can I downgrade?

**Comment by alexmccabe** [comment]
Okay so ignore my previous screenshot, I didn't know that SublimeLinter copies the current syntax highlighting and forces you to use it's own version. Switching to your one I get a similar result to @matejkramny 
![screenshot 2016-02-15 09 21 01](https://cloud.githubusercontent.com/assets/2529110/13044327/768175d0-d3c5-11e5-8eb4-35f58c6fbaf8.png)
