### ISSUE TITLE
Bug with scrollbars

### ISSUE THREAD

**Issue by cawa-93** [jamiewilson/predawn#123]
After update predawn to v2.0.2

![2016-02-09 20 20 06](https://cloud.githubusercontent.com/assets/1662812/12926118/8a36bfcc-cf6a-11e5-9626-51c9c22595bb.png)

**Comment by jamiewilson** [comment]
@cawa-93 Did you restart sublime already?

**Comment by cawa-93** [comment]
@jamiewilson, I tried to restart the editor and change the color scheme.

![2016-02-09 20 27 36](https://cloud.githubusercontent.com/assets/1662812/12926312/961ae128-cf6b-11e5-978c-2fd2140c6d42.png)
![2016-02-09 20 27 41](https://cloud.githubusercontent.com/assets/1662812/12926310/95fe0a62-cf6b-11e5-92ee-b3e398dbe615.png)

**Comment by jamiewilson** [comment]
Ah. There's actually a [predawn-DEV version for all builds at 3062+](https://github.com/jamiewilson/predawn#activating-the-theme) since there were some major changes to the sidebar after 2.x. So if you change your `theme` to `predawn-DEV.sublime-theme`, you should be okay. Let me know!

**Comment by mattst** [comment]
Please note that the same problem exists with Sublime Text v2 (latest build 2221) after the Predawn 2.0.2 update.

The horizontal scroll bars are also corrupt if they are being displayed.

Changing the ST v2 theme to the Predawn `dev` version seems to have resolved the issue. Is there any reason why the `dev` version should not be used with ST v2?

Here's what it looks like using `"theme": "predawn.sublime-theme"`:

![predawn_theme_bug_in_subtext_v2_ 1](https://cloud.githubusercontent.com/assets/835623/12927924/b8454f4e-cf62-11e5-8f09-e06ad1b81d2c.png)

![predawn_theme_bug_in_subtext_v2_ 2](https://cloud.githubusercontent.com/assets/835623/12927932/be0a9308-cf62-11e5-9e41-77ecd9496e82.png)

**Comment by jamiewilson** [comment]
@mattst Yeah, the reason is that version 3 of sublime text is still in beta  (and introduces some fundamental changes to the way the sidebar works. I've tried to learn of a better to support both, but have yet to find any good solutions. 

So you are using ST3 and `predawn-DEV.sublime-theme` fixes your issues with sidebar?

**Comment by mattst** [comment]
@jamiewilson 

> So you are using ST3 and predawn-DEV.sublime-theme fixes your issues with sidebar?

I use both ST v2 and v3.

**With ST v3**: I have been using `predawn-DEV.sublime-theme` for a long time and have no issue with the updates you have made today; it works fine.

**With ST v2**: I had been using `predawn.sublime-theme` - my screenshots above show the bar bug with Predawn 2.0.2. Changing to `predawn-DEV.sublime-theme` resolved the bar bug but the tab bar background colour does not work. After the Predawn 2.0.3 update I switched back to `predawn.sublime-theme` the corrupt sidebar is now displayed properly but the theme no longer shows the orange slider of the horizonontal bar at all - the area the orange slider of the bar should be displayed inside is shown but the orange slider itself is missing.

HTH.
