### ISSUE TITLE
How to downgrade to pre-JS highlighting issues

### ISSUE THREAD

**Issue by matejkramny** [jamiewilson/predawn#125]
What can I do to get the old highlighter back?

**Comment by jamiewilson** [comment]
If you get the latest version from package control, I've tried to bring it back to what it was. https://github.com/jamiewilson/predawn/releases/tag/2.0.4

**Comment by matejkramny** [comment]
Cool, thanks!

I really appreciate your work @jamiewilson, can you explain what's going on? :)

**Comment by jamiewilson** [comment]
@matejkramny As far as I can tell, ST revised some of the scopes that are used for syntax highlighting so I had to update my theme file to use the new scope names.

**Comment by roc** [comment]
@jamiewilson still looking a bit odd for me after upgrading to `2.0.4` but definitely improved, thank you :pray: 

![screen shot 2016-02-12 at 12 09 46](https://cloud.githubusercontent.com/assets/120181/13006557/a3a51f8a-d181-11e5-9f65-8e5b66082c0c.png)

**Comment by matejkramny** [comment]
Hmm I think the solution would be to:

1. Downgrade sublime to [3083](https://download.sublimetext.com/Sublime%20Text%20Build%203083.dmg)
2. manually downgrade Predawn somehow. Patch files manually i think

I've swapped to Atom briefly while this is figured out. If you'd like any help @jamiewilson, would love to do something about it!

**Comment by jamiewilson** [comment]
Let me know if you all are still unhappy with the JS syntax highlighting.
