### ISSUE TITLE
Theme not working with build 3103 (Sublime OSX)

### ISSUE THREAD

**Issue by cherrylipstick** [jamiewilson/predawn#128]
The theme is not working anymore after I updated to build 3103. The sidebar and tabs styles are not working anymore, I could make it work for the color_scheme only.

Is anyone else having this issue? Thanks in advance.

**Comment by MadMacMad** [comment]
it works just fine here!
build 3105 OS X 
delete the Sublime Text folder under Application Support then reinstall the theme...
to this is by far the best theme i know!
made my own color theme for Unity3d... works perfect to me...
https://raw.githubusercontent.com/MadMacMad/Unity3d-Sublime-Text-3-color-theme/master/_Unity3d_Holle_Dark.tmTheme

**Comment by marshfire** [comment]
I'm also having problems with the 3103 and the latest preDawn. The folder icons are not orange anymore, but only have a black outline. This happens on Win7 x64 as well as on Ubuntu 14.04. 

![image](https://cloud.githubusercontent.com/assets/681471/13664088/8a140048-e6a5-11e5-8010-6da28dd85cf4.png)

**Comment by marshfire** [comment]
changing the theme to 

	"theme": "predawn-DEV.sublime-theme"

fixed it for me.

**Comment by cherrylipstick** [comment]
Mine still looks like this when I try to install Predawn
![screen shot 2016-03-11 at 16 00 44](https://cloud.githubusercontent.com/assets/5595322/13712513/d3bbd772-e7a2-11e5-8523-f08d28740966.png)
