### ISSUE TITLE
resize tab width based on opened tabs

### ISSUE THREAD

**Issue by nasr18** [jamiewilson/predawn#133]
In default theme, based on opened tabs, the tab width size will change to show most of the tabs. but in your theme, tab size not resizing based on opened tabs. So everytime i have to click on `down arrow` next to last tab's right side corner. Please fix it. Other than this, its just awesome.

**Comment by jamiewilson** [comment]
hmm. What OS are running? Can you add a screenshot or screencast so I can see what you're referring too? Here's one showing my tabs resizing as I close them. http://quick.as/4zprcaxgq

**Comment by nasr18** [comment]
sorry dude. no issues. sorry for posting. misunderstood.

**Comment by jamiewilson** [comment]
No worries!
