### ISSUE TITLE
Folder icon and small tab setting not working in 3129

### ISSUE THREAD

**Issue by tkaw220** [jamiewilson/predawn#147]
Folder icon in side panel and small tab are breaking in build 3129.

![predawn](https://cloud.githubusercontent.com/assets/694289/25116452/75003d4c-243f-11e7-9930-fb5dbd1b1e13.PNG)

**Comment by MikeMcChillin** [comment]
Same here. A quick & dirty fix is to just include all the options. For whatever (inheritance?) reason, this seemed to work for me:
```
"predawn_sidebar_arrows": false,
  "predawn_sidebar_large": false,
  "predawn_sidebar_medium": false,
  "predawn_sidebar_narrow": false,
  "predawn_sidebar_small": true,
  "predawn_sidebar_xlarge": false,
  "predawn_sidebar_xsmall": false,
"predawn_tabs_active_underline": false,
	"predawn_tabs_large": false,
	"predawn_tabs_medium": false,
	"predawn_tabs_small": true,
```

**Comment by anatomatic** [comment]
You can also put a predawn-DEV.sublime-theme file in your User/ folder. Any classes there should override the package installed theme.

Here's [a gist](https://gist.github.com/anatomatic/2663ac74ff5af0558f35bfef789767eb) with the fix.
