### ISSUE TITLE
ST update seems to mess up folder icons

### ISSUE THREAD

**Issue by eheiser** [jamiewilson/predawn#150]
The latest sublime text update seems to break the folder icons - see screenshot. FYI
![screenshot_01](https://user-images.githubusercontent.com/86934/30381529-f6f30312-989c-11e7-8c8c-4aed628a8fee.png)

**Comment by jamiewilson** [comment]
Hmm, just updated as well and didn't get this issue. You're talking about Version 3.0 Build 3143 right? Make sure your settings specify `"theme": "predawn-DEV.sublime-theme"` and let me know if you're still having issues.

**Comment by eheiser** [comment]
That did it - many thanks!

**Comment by jamiewilson** [comment]
🎉
