### ISSUE TITLE
Side bar icons glitches

### ISSUE THREAD

**Issue by JordanDelcros** [jamiewilson/predawn#152]
I just installed the last stable release of Sublime Text 3 and since I've did it I got that beautifull glitche only in the side bar icons:

![capture d ecran 2017-09-15 a 09 23 25](https://user-images.githubusercontent.com/4179270/30471122-c531f9bc-99f7-11e7-9c98-d65e6fd8e678.png)

Glad it's easy to fix...

Thanks for that nice theme.

**Comment by jamiewilson** [comment]
Make sure your settings specify `"theme": "predawn-DEV.sublime-theme"` and let me know if you're still having issues.

**Comment by JordanDelcros** [comment]
Yep, fixed the theme. Thanks!
