### ISSUE TITLE
visual studio code

### ISSUE THREAD

**Issue by adnasa** [jamiewilson/predawn#161]
I've been looking around in the issues, but couldn't anything that discusses this.
but any chance we get to see this ported to [code](https://code.visualstudio.com)?

**Comment by tkaw220** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-vscode.Theme-PredawnKit

**Comment by adnasa** [comment]
@tkaw220 thanks man. appreciate the fast response.
Closing 😉
