### ISSUE TITLE
Console and goto panel adjustments

### ISSUE THREAD

**Issue by paulikt** [jamiewilson/predawn#44]
It would be good to make the size of the console and the "goto anything panel" (and it's variations like command palette) adjustable back to the sublime originals, just as it is possible with the tabs and the find panel.

Or maybe I overlooked something, but I can't find the option.

**Comment by raejin** [comment]
Hi,
I would like to have it adjustable as well. Sometimes when using Cmd+P, I'd like to see more items on the list whenever possible.
Thanks for making this awesome theme!

**Comment by jamiewilson** [comment]
look for a `predawn_quick_panel_small` in the next release :)
