### ISSUE TITLE
Adjust line padding in the find/replace bar.

### ISSUE THREAD

**Issue by max-g** [jamiewilson/predawn#46]
When using a custom line_padding_top/line_padding_bottom it affects the find/replace input fields and make them unaligned with the buttons. I don't know if it would be possible to either make the buttons aligned with the fields, or ignore the custom line_paddings settings.

![screen shot 2014-08-15 at 9 59 21](https://cloud.githubusercontent.com/assets/2347985/3933837/732e4058-2484-11e4-994e-61441cce1097.png)

**Comment by jamiewilson** [comment]
so, I think if you just manually adjust the vertical height of the find and replace panel by dragging the top edge up, it should honor the changes to the padding and not cut anything off. Hope that helps!
