### ISSUE TITLE
Latest update removed sidebar icons

### ISSUE THREAD

**Issue by CountZachula** [jamiewilson/predawn#52]
The latest (automatic) predawn update killed the sidebar icons. Am I supposed to update my config with a new flag?

Any help would be much appreciated.

```
{
"caret_style": "phase",
"color_scheme": "Packages/Colorsublime-Themes/FireCode.tmTheme",
"draw_minimap_border": true,
"font_face": "Ubuntu Mono",
"font_options":
[
    "subpixel_antialias",
    "no round"
],
"font_size": 14,
"highlight_line": true,
"highlight_modified_tabs": true,
"ignored_packages":
[
    "Vintage"
],
"line_padding_bottom": 1,
"line_padding_top": 1,
"rulers":
[
    128
],
"scroll_past_end": true,
"tab_completion": false,
"tab_size": 4,
"theme": "predawn.sublime-theme",
"trim_trailing_white_space_on_save": true,
"word_wrap": false
}
```

![screen shot 2014-08-24 at 4 29 19 pm](https://cloud.githubusercontent.com/assets/2559507/4024702/d61b4adc-2bd5-11e4-9872-9cecde5cf33c.png)

**Comment by fbcom** [comment]
Well something broken again in 3103. However, using
`    
"theme": "predawn-DEV.sublime-theme",
"color_scheme": "Packages/Predawn/predawn.tmTheme"
`
in preferences fixed it for me.

**Comment by derekbrown** [comment]
Just updating on this issue for the latest Sublime update (Sept 2017 - official Sublime Text 3). Changing the `theme` setting to the following restored the sidebar folders:

`"theme": "predawn-DEV.sublime-theme"`

**Comment by jtclegg** [comment]
Like @derekbrown , just updated to Build 3143 (Sept 2017) and lost .js, .css. .scss, .json, .cmd and .sublime-project icons in the sidebar.

Setting theme to predawn-DEV doesn't fix the problem. 

Folder and .html, .png, .svg and a few others appear fine.
