### ISSUE TITLE
Sidebar scrollbar not so clean

### ISSUE THREAD

**Issue by kud** [jamiewilson/predawn#61]
Is it possible to make it cleaner? The scrollbar should maybe go on all the top of the window.

![screen shot 2014-09-01 at 11 15 55](https://cloud.githubusercontent.com/assets/655838/4106316/a333ad74-31b8-11e4-96f4-6c2eb24c2f9f.png)

**Comment by jamiewilson** [comment]
Should be fixed in the next release!
