### ISSUE TITLE
Huge margin-left on file icons

### ISSUE THREAD

**Issue by welcoMattic** [jamiewilson/predawn#62]
Hi! 

There is a huge margin-left on file icons like that :
![image](https://cloud.githubusercontent.com/assets/773875/4136068/83469c64-337b-11e4-89ae-cd19196da1fe.png)

Can you fix it quickly ? It's a bit boring :/

CONFIG : 

OS X 10.10 DP7
ST3 build 3065

**Comment by jamiewilson** [comment]
should be fixed with next release.
