### ISSUE TITLE
Weird behavior on HTML file preview

### ISSUE THREAD

**Issue by zigolis** [jamiewilson/predawn#64]
Hey guys,
First of all congrats for the great and lovely job on this theme, I don't know why, but something weird is happening only in HTML files. I've printed two open tabs (HTML / JS).

![screenshot 2014-09-04 15 36 58](https://cloud.githubusercontent.com/assets/2637502/4154550/7e9855f8-3462-11e4-99f0-c0073b67275d.png)

Have you ever seen something like that?

If not, i'm gonna remove the theme and install again! Ahh...

Thanks

**Comment by jamiewilson** [comment]
I haven't reproduced this problem myself and haven't heard any other reports. I'll close for now, but let me know if you still need help.
