### ISSUE TITLE
Underline active tab.

### ISSUE THREAD

**Issue by mattst** [jamiewilson/predawn#65]
Enhancement request... I very much like the way that 'Numix Theme' (as opposed to 'Theme - Numix' which is different) underlines the active tab. It would be great if Predawn could have that available as an option with the underlining done in the predawn peachy/orange theme colour. In my opinion it would look really great. :) Thanks for the great theme, it's by far my favourite and, since discovering it a few months ago, it's the only theme I've used.

![st_numix_theme_underline_active_tab](https://cloud.githubusercontent.com/assets/835623/4163586/1f13793c-34e9-11e4-98bb-3fb05c25aa70.png)

Image screen captured from:
https://sublime.wbond.net/packages/Numix%20Theme

**Comment by gom3z** [comment]
That would be great !

**Comment by jamiewilson** [comment]
I think I'll add this into the next release as an option. Thanks for the requests!

**Comment by papucho** [comment]
+1

**Comment by davidsuh79** [comment]
Has this been implemented in recent version? I love this underline feature!

**Comment by jamiewilson** [comment]
Next release includes this. Coming soon!
