### ISSUE TITLE
Dock icons, not clear how to change them

### ISSUE THREAD

**Issue by radaniba** [jamiewilson/predawn#66]
Hi There,

Is it possible to explain that part in the readme file as well, like the other options ?

Thanks

**Comment by jamiewilson** [comment]
You should be able to find a decent tutorial on how to update mac dock icons on the google :-)

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=how+to+change+mac+dock+icons

**Comment by radaniba** [comment]
Thanks @jamiewilson
