### ISSUE TITLE
Sidebar files/folders alignment

### ISSUE THREAD

**Issue by cachitas** [jamiewilson/predawn#70]
What is wrong with the sidebar?

My theme does not match what you have in the README.md example.

Your example:
![readme](https://raw.githubusercontent.com/jamiewilson/predawn/master/screenshots/screenshot.png)

Mine:
![sidebar](https://cloud.githubusercontent.com/assets/2321514/4425241/87c3249a-45a7-11e4-8ae8-e73d3801e535.png)

Is this what everyone else gets? Am I missing something?

**Comment by jamiewilson** [comment]
Will definitely move the DEV theme into master when I push the next release!

**Comment by ravikumars** [comment]
Any updates on this? It still shows mis-aligned files in ```predawn.sublime-theme```.

**Comment by jamiewilson** [comment]
@ravikumars Are you using ST2 or ST3. Since ST3 is still in beta I think I'll keep the `predawn-DEV.sublime-theme` for now.

**Comment by ravikumars** [comment]
I am actually using ST3. I will use predawn-DEV for now. Thanks.
