### ISSUE TITLE
File icons indented awkwardly in Sidebar

### ISSUE THREAD

**Issue by bom-d-van** [jamiewilson/predawn#71]
This is mine:

![screen shot 2014-10-14 at 6 02 31 pm](https://cloud.githubusercontent.com/assets/459505/4627271/789866d4-5389-11e4-8ef3-007e25c727a3.png)

This is the correct one:

![](https://raw.githubusercontent.com/jamiewilson/predawn/master/screenshots/screenshot.png)

**Comment by mbrodala** [comment]
I didn't notice this issue and created #84 (closed now). I assume that `predawn-DEV.sublime-theme` is the current development state. Will there be a release note if the fix goes into the release theme?
