### ISSUE TITLE
Tighten up sidebar's horizontal space (not just vertical)

### ISSUE THREAD

**Issue by brendanfalkowski** [jamiewilson/predawn#72]
I know there's an option for vertical spacing (I like xsmall). Scrolling isn't much of an issue for me, but my projects (Magento) have very deep trees.

So my sidebar sometimes needs to be excessively wide to view the tree. In other themes the sidebar is more compact horizontally. It'd be nice if the folder icons were downsized to match the file icons and the spacing was tightened up as much as possible while still representing the hierarchy.

**Comment by jamiewilson** [comment]
Thanks for the request. I've had an issue with that on deeper projects too. Will take a look!

**Comment by dealingwith** [comment]
My issue is files have extra indentation compared to folders, so files look at first glance to be children of child folders. For example, in the below screenshot, `index.hbs` is a child of "property", not "recent_activity", but that is unclear...

![screen shot 2015-01-27 at 1 13 34 pm](https://cloud.githubusercontent.com/assets/124208/5925037/55b3b14c-a626-11e4-9206-afba0056176f.png)

**Comment by jamiewilson** [comment]
@dealingwith Ah, yeah. That was a weird thing that was going on with the changes from versions without icons. You can immediately fix this by setting you theme to `"theme": "predawn-DEV.sublime-theme"`, but I hope to merge those two versions in the near future.

**Comment by dealingwith** [comment]
Yeah I'm noticing other themes with icons have the same issue. :confused:

**Comment by papucho** [comment]
Yeah, the horizontal space fix would be awesome! :+1:

**Comment by paulikt** [comment]
Is there a like button somewhere? Anyway making the tree more compact horizontally would be a nice addition

**Comment by zackcote** [comment]
@paulikt typically if you want to 'like' something on github, comment with a :+1: (which you get by typing `:+1:`

**Comment by jamiewilson** [comment]
Next release will have this! Stay tuned.
