### ISSUE TITLE
Default scrollbars?

### ISSUE THREAD

**Issue by brianyuen** [jamiewilson/predawn#73]
Hello,
Love the Predawn theme. Thank you for making this.  Currently using ST3 on OSX Yosemite, is there a way to revert back to the normal default scrollbars. The thin orange scrollbars aren't doing it for me and I much prefer the default style scrollbars in ST3.

Thank you!

**Comment by jamiewilson** [comment]
Hey @brianyuen, you could just replace the scrollbar files in Predawn/assets/... with these images: http://cl.ly/ZPLB/default-scrollbars.zip
