### ISSUE TITLE
Question: Is there a .psd for the icons?

### ISSUE THREAD

**Issue by aeikenberry** [jamiewilson/predawn#77]
I'd like to add a rust .rs file type icon. What's the best way to go about that. (I am not a graphics person, but if there was a template where i could just go in and change some text and save, that'd be ideal!)

Thanks! Really nice theme.

**Comment by jamiewilson** [comment]
No .psds :-) but you can get the illustrator files here: https://github.com/jamiewilson/predawn-icons
