### ISSUE TITLE
Lots of Tabs ST2

### ISSUE THREAD

**Issue by alexmccabe** [jamiewilson/predawn#78]
In Sublime Text 2 if you have lots of tabs open, you cannot get to the ones that are off screen. In other themes, I never noticed that it was hiding any tabs. 

I have a large project structure, and having to scroll to the top of it gets frustrating after a while. I love the theme and colour scheme, it works very well, but this is the one thing that I have a problem with. 

I'm not sure if there is a work around.

**Comment by jamiewilson** [comment]
Hey, thanks for letting me know about this. I think I might have run into this problem once or twice myself, but didn't think it was because of Predawn. Doh!

**Comment by alexmccabe** [comment]
You're welcome. I've been using cmd+p as a work around for now.

**Comment by radzinzki** [comment]
@alexmccabe you can fix that by setting `enable_tab_scrolling` to `true` in your sublime text preferences. 

In the install notes, @jamiewilson recommends setting it to `false`. You may have copy pasted it like I did. 

I hope this helps :)

@jamiewilson, if you'd like, I could make a PR to remove that setting from the install notes. Cheers!

**Comment by alexmccabe** [comment]
At the time I was using ST2. Since switching to ST3 this has been a non-issue for me, but it should be noted for users of ST2.
