### ISSUE TITLE
Adapt the font size of the search field

### ISSUE THREAD

**Issue by awenro** [jamiewilson/predawn#81]
Hey,

I'd like to increase the font size of the search field since its quite small, but I couldn't find the setting in the theme file. Could you be so kind as to give me hint, please?

Best,
Alex

**Comment by jamiewilson** [comment]
This actually isn't a setting in the theme file, but you can manually change it at `Packages/Predawn/assets/Widget - predawn.sublime-settings` (or `Widget - predawn-DEV.sublime-settings` depending on which one you are using.
