### ISSUE TITLE
Vim color theme?

### ISSUE THREAD

**Issue by ofcapl** [jamiewilson/predawn#82]
Is there any chance that Predawn will be released as a vim color theme?

**Comment by jamiewilson** [comment]
I probably won't do that myself as I'm not a VIM user. But if there's enough demand :)

**Comment by shbm** [comment]
Like many of vim users I would love to see it as a vim color theme. +1

**Comment by zxr90** [comment]
+1 for vim color theme

**Comment by renechz** [comment]
I ported it to vim using https://github.com/sickill/coloration
You can take a look here - https://gist.github.com/renechz/fc6806cc11ba41c6c6e8

**Comment by jamiewilson** [comment]
Thanks for the port @renechz !
