### ISSUE TITLE
Certain things appear gray like comments

### ISSUE THREAD

**Issue by zackphilipps** [jamiewilson/predawn#86]
I love this theme so much, so great work and thank you! The only downside I've noticed so far is that `=` and `!` in PHP show up as gray in color (as if they are part of a code comment), whereas with Flatland I'm almost positive they were a different color. I do have Markdown enabled but since the options for that are syntax-specific I wouldn't think that would be the issue.

**Comment by zackphilipps** [comment]
`->` as in `$query->have_posts()` and `as` in `foreach` loops qualify as well.

**Comment by zackphilipps** [comment]
![screen shot 2015-03-31 at 17 13 32](https://cloud.githubusercontent.com/assets/3578812/6929518/5e2af2e8-d7c9-11e4-84c8-e190e1bde174.png)
![screen shot 2015-03-31 at 17 14 07](https://cloud.githubusercontent.com/assets/3578812/6929520/5e2ea7c6-d7c9-11e4-8dc9-d604bd1ba961.png)
![screen shot 2015-03-31 at 17 13 53](https://cloud.githubusercontent.com/assets/3578812/6929519/5e2d169a-d7c9-11e4-9527-01737e492e3f.png)

**Comment by jamiewilson** [comment]
Cool. thanks for the input. I'll see if I can work in a change to this in the next release.

**Comment by zackphilipps** [comment]
Awesome, you're the man!


Zack PhilippsExecutive Director at Tribeswell

zack@tribeswell.com

812.797.9545

**Comment by zackphilipps** [comment]
![screen shot 2015-04-01 at 14 42 24](https://cloud.githubusercontent.com/assets/3578812/6948697/6d089f72-d87d-11e4-8f71-520829eab9f4.png)

Also happens to images in markdown.

**Comment by jamiewilson** [comment]
Some of this should be covered in the next release. Thanks again for the help!
