### ISSUE TITLE
More icons.

### ISSUE THREAD

**Issue by leiserfg** [jamiewilson/predawn#89]
There is not python icon, I can draw it, if I do can I mail it to you?

**Comment by stickyhands** [comment]
+ 1!
lots of icons are missing:
- .yml
- .gitignore
- Dockerfile
- .twig

and probably more

**Comment by sos0** [comment]
.jsp :+1:

**Comment by brousalis** [comment]
.coffee
.json

**Comment by yangkghjh** [comment]
.json

2015-06-24 1:06 GMT+08:00 Pete Brousalis <notifications@github.com>:

**Comment by paulikt** [comment]
Just to add a few to the list:
.md
.sql
.tmp
.groovy
.properties, .conf (could be the same as the one that is used for json - the one with the toggles(?))
.ldif
.mustache
.java

And not development related, but I work a lot with these: .key, .cer, .pfx, .jks, .pem

**Comment by delliriun** [comment]
@leiserfg make a fork, I dont think he intends to support python.

**Comment by Lonelind** [comment]
.styl — i need this extension

**Comment by jamiewilson** [comment]
I'll keep these on the list for new file icons. Also, check out this repo for icon related stuff: https://github.com/jamiewilson/predawn-icons
