### ISSUE TITLE
Misalignment issues

### ISSUE THREAD

**Issue by andyjessop** [jamiewilson/predawn#91]
Using ST2 on Ubuntu 14.04, I get [overlapping at the bottom](http://i.imgur.com/fdG7Dpn.png), and a [misalignment with the scrollbar for the sidebar](http://i.imgur.com/kERPmkG.png).

**Comment by jamiewilson** [comment]
Check out #21 for the find/replace overlap. Not sure about the scroll bar issue. I'll look into it. Thanks!

**Comment by andyjessop** [comment]
Ah, got it - thanks.
