### ISSUE TITLE
Missing 'file modified' icon

### ISSUE THREAD

**Issue by dreamone4** [jamiewilson/predawn#93]
On the tab with the filename, there is a cross-icon for closing the tab. When I modify a file, the cross used to change into a bullet so that I could see the file was modified and not yet saved. When installing predawn, this behavior changed, and there is no way to see if the file is modified other than trying to close it.

**Comment by jamiewilson** [comment]
The way you can tell if a file is "dirty" is that the close icon turns orange. Unmodified tabs have a grey close icon. As seen here:

![screen shot 2015-05-29 at 11 13 38 am](https://cloud.githubusercontent.com/assets/3308673/7887068/ef191296-05f3-11e5-83cc-7516eef51c15.png)

Is that working?

**Comment by dreamone4** [comment]
Yes. Was expecting different behavior, that's probably why I overlooked. My bad.

**Comment by jamiewilson** [comment]
np :)

**Comment by srigi** [comment]
Can this be changed? In original Soda theme dirty tab is indicated by bullet • character.
I'm used to such behavior, only changed color on dirty tab is not working for me after years on Soda.
