### ISSUE TITLE
Adjust tab text margins to fit greater font size

### ISSUE THREAD

**Issue by markreg** [jamiewilson/predawn#96]
I'm using ST3 3059 and I'm using PackageResourceViewer to adjust the font size of the tab text in predawn.sublime-theme under `tab_label`.

However, some unknown tab margin setting is cutting the text off if I set it greater than 11.

Which setting should I change to allow the increased tab text to fit in the tab? Thanks.

**Comment by jamiewilson** [comment]
I'm not exactly sure how to resolve your issue. But you'd probably need to play around with the values here: https://github.com/jamiewilson/predawn/blob/master/predawn.sublime-theme#L37
