### ISSUE TITLE
Sidebar file/folder list indent/alignment seems odd

### ISSUE THREAD

**Issue by dotZoki** [jamiewilson/predawn#98]
Files indentation is off and causes visual confusion. It seems that it starts one level down. Look at the attached image
![sidebar](https://cloud.githubusercontent.com/assets/247270/8909803/aadf0f9a-3483-11e5-90a6-7e5faf147987.jpg)
`.gitignore` file should be same level as `app` folder, `test.js` should be same level as `vinyl-source-stream/node_modules` folder etc..

OS: windows 8.1
Sublime 3 build 3083

**Comment by jamiewilson** [comment]
Right now, Predawn ships with two versions of the theme. One for earlier versions without sidebar icons and a DEV version that was created when icons were still in development. you can reference:

```
"theme": "predawn-DEV.sublime-theme"
```
for now. I'll eventually make this the default then more people move to ST3.

**Comment by dotZoki** [comment]
Oh, I see that copied the wrong theme name from docs :)

Sorry and thanks for replying
